"""Generate config/configs_gta/* from S02 ablation templates + GTA dataset paths.

Usage:
    python scripts/generate_configs_gta.py
"""
from __future__ import annotations

import copy
import sys
from pathlib import Path

import yaml

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

OUT_ROOT = _ROOT / "config" / "configs_gta"
GTA_SOURCES = [f"datasets/gta_mcmt/cam-{i}" for i in range(4)]
GTA_HOMOS = [f"datasets/gta_mcmt/cam-{i}/calibration.txt" for i in range(4)]

SOURCE_GLOBS: list[tuple[str, str]] = [
    ("config/gta_mcmt_baseline.yaml", "baseline.yaml"),
    ("config/gta_mcmt_2k.yaml", "gta_mcmt_2k.yaml"),
    ("config/gta_mcmt_smoke.yaml", "gta_mcmt_smoke.yaml"),
    ("config/s02_baseline/sort/yolov8m.yaml", "sort/yolov8m.yaml"),
]

SOURCE_DIRS: list[tuple[str, str]] = [
    ("config/assoc_ablation", "assoc_ablation"),
    ("config/reid_ablation", "reid_ablation"),
    # geo_ablation: generated by scripts/generate_geo_ablation_configs.py (GTA-calibrated thresholds)
    ("config/ema_vs_aaf", "ema_vs_aaf"),
    ("config/baseline_trackers", "baseline_trackers"),
    ("config/latency_ablation", "latency_ablation"),
    ("config/s02_baseline/deepocsort/detectors", "deepocsort/detectors"),
    ("config/s02_baseline/ocsort/detectors", "ocsort/detectors"),
]


def _collect_sources() -> list[tuple[Path, Path]]:
    pairs: list[tuple[Path, Path]] = []
    for src_rel, dst_rel in SOURCE_GLOBS:
        pairs.append((_ROOT / src_rel, OUT_ROOT / dst_rel))
    for src_dir, dst_dir in SOURCE_DIRS:
        root = _ROOT / src_dir
        if not root.is_dir():
            continue
        for src in sorted(root.iterdir()):
            if src.suffix not in {".yaml", ".yml"}:
                continue
            pairs.append((src, OUT_ROOT / dst_dir / src.name))
    return pairs


def _rewrite_run_comment(text: str, dst_rel: Path) -> str:
    dst_posix = dst_rel.as_posix()
    lines = text.splitlines()
    out: list[str] = []
    for line in lines:
        if line.startswith("# Run:") and "run.py --config" in line:
            out.append(f"# Run: python run.py --config {dst_posix}")
        elif line.startswith("# Eval:") and "eval_s02" in line:
            out.append(
                f"# Eval: python scripts/eval_gta_mcmt.py --pred-dir "
                f"outputs/configs_gta/<run>/per_cam --apply-roi"
            )
        else:
            out.append(line)
    if out and not out[0].startswith("# GTA MCMT"):
        out.insert(0, "# GTA MCMT ablation (generated from S02 template)")
    return "\n".join(out) + "\n"


def _patch_zones_path(value: str) -> str:
    if "zone_tracklet" in value:
        return "configs_gta/gta_zone_tracklet.yaml"
    if "zone_polygon" in value or value.endswith("s02_zone_polygons.yaml"):
        return "configs_gta/gta_zone_polygons.yaml"
    return value


def _remap_output_path(path: str) -> str:
    if path.startswith("outputs/"):
        return "outputs/configs_gta/" + path[len("outputs/") :]
    return path


def _optional_float(value) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _uses_tiered_geometry(mc: dict) -> bool:
    assoc = mc.get("association")
    if isinstance(assoc, dict):
        t_distant = _optional_float(assoc.get("geometry_t_distant_m"))
        if t_distant is not None and t_distant > 0:
            return True
    legacy = _optional_float(mc.get("geometry_max_distance"))
    return legacy is not None and legacy > 0


def _strip_legacy_assoc(assoc: dict) -> None:
    gates = assoc.get("gates")
    if isinstance(gates, dict):
        for key in ("different_cam", "geometry_overlap"):
            gates.pop(key, None)
    assoc.pop("gate_mode", None)
    assoc.pop("geometry_max_distance_m", None)


def _migrate_association_block(mc: dict) -> None:
    assoc = mc.get("association")
    if not isinstance(assoc, dict):
        legacy_dist = _optional_float(mc.get("geometry_max_distance"))
        legacy_cost = _optional_float(mc.get("association_cost_threshold"))
        if legacy_dist is None and legacy_cost is None:
            return
        assoc = {}
        mc["association"] = assoc
    else:
        assoc = dict(assoc)
        mc["association"] = assoc

    gates = dict(assoc.get("gates") or {})
    assoc["gates"] = gates
    gates.setdefault("temporal", False)
    gates.setdefault("cam_transition", False)
    gates.setdefault("zone_transition", False)

    assoc.setdefault("reid_matching", True)

    if "reid_cost_threshold" not in assoc:
        legacy_cost = _optional_float(mc.get("association_cost_threshold"))
        if legacy_cost is not None:
            assoc["reid_cost_threshold"] = legacy_cost

    if "max_cross_cam_gap_frames" not in assoc:
        legacy_gap = mc.get("max_cross_cam_gap_frames")
        if legacy_gap is not None:
            assoc["max_cross_cam_gap_frames"] = legacy_gap

    if _uses_tiered_geometry(mc):
        legacy_dist = _optional_float(mc.get("geometry_max_distance"))
        t_distant = _optional_float(assoc.get("geometry_t_distant_m"))
        if t_distant is None or t_distant <= 0:
            if legacy_dist is not None and legacy_dist > 0:
                assoc["geometry_t_distant_m"] = legacy_dist
                assoc.setdefault("geometry_t_min_m", round(legacy_dist * 0.37, 1))
            else:
                assoc.setdefault("geometry_t_min_m", 14.0)
                assoc.setdefault("geometry_t_distant_m", 38.0)
        assoc.setdefault("geometry_distance_metric", "plane")
        assoc.setdefault("geometry_mid_penalty", 0.15)
        assoc.setdefault("same_cam_cost_add", 0.25)
    else:
        assoc.setdefault("geometry_distance_metric", "plane")
        assoc.setdefault("geometry_t_min_m", 14.0)
        assoc["geometry_t_distant_m"] = 0.0
        assoc.setdefault("geometry_mid_penalty", 0.15)
        assoc.setdefault("same_cam_cost_add", 0.25)

    _strip_legacy_assoc(assoc)
    mc.pop("geometry_max_distance", None)
    mc.pop("association_cost_threshold", None)
    mc.pop("association_reid_weight", None)


def patch_config(cfg: dict, dst_rel: Path) -> dict:
    cfg = copy.deepcopy(cfg)
    mc = cfg.setdefault("multi_camera", {})
    mc["cam_ids"] = [0, 1, 2, 3]
    mc["sources"] = list(GTA_SOURCES)
    mc.setdefault("roi", "auto")

    preserve_geo = _uses_tiered_geometry(mc)
    if preserve_geo:
        mc["homos"] = list(GTA_HOMOS)
    else:
        mc["homos"] = None

    _migrate_association_block(mc)

    assoc = mc.get("association")
    if isinstance(assoc, dict) and assoc.get("zones_path"):
        assoc["zones_path"] = _patch_zones_path(str(assoc["zones_path"]))

    if mc.get("results_dir"):
        mc["results_dir"] = _remap_output_path(str(mc["results_dir"]))
    else:
        mc["results_dir"] = f"outputs/configs_gta/{dst_rel.with_suffix('').as_posix()}"

    out = cfg.setdefault("output", {})
    for key in ("output_path", "save_video_dir"):
        if out.get(key):
            out[key] = _remap_output_path(str(out[key]))

    return cfg


def write_gta_zone_polygons() -> None:
    tracklet = yaml.safe_load(
        (OUT_ROOT / "gta_zone_tracklet.yaml").read_text(encoding="utf-8")
    )
    snapshot = copy.deepcopy(tracklet)
    snapshot["mode"] = "snapshot"
    text = yaml.dump(snapshot, sort_keys=False, allow_unicode=True)
    header = (
        "# GTA MCMT zone graph (snapshot mode): zone at handoff time.\n"
        "# Same polygons/transitions as gta_zone_tracklet.yaml.\n\n"
    )
    (OUT_ROOT / "gta_zone_polygons.yaml").write_text(header + text, encoding="utf-8")


def write_zone_tracklet_run_config() -> None:
    """Standalone zone tracklet ablation (ReID + zone graph)."""
    cfg = {
        "run_mode": "multi_camera",
        "detector": {
            "model": "models/yolo26l_fine_tune_gta.pt",
            "target_classes": [2, 3, 5, 7],
            "conf_thres": 0.2,
            "imgsz": 640,
            "device": 0,
        },
        "tracker": {
            "type": "deepocsort",
            "use_embeddings": True,
            "reid_weights": "models/osnet_ibn_x1_0_msmt17.pt",
            "device": 0,
            "half": False,
            "det_thresh": 0.3,
            "max_age": 30,
            "min_hits": 3,
            "iou_threshold": 0.3,
            "appearance_update": "aaf",
            "reid_accum_conf_thresh": 0.5,
        },
        "multi_camera": {
            "cam_ids": [0, 1, 2, 3],
            "sources": GTA_SOURCES,
            "homos": None,
            "roi": "auto",
            "max_frames": None,
            "association": {
                "gates": {
                    "temporal": False,
                    "cam_transition": False,
                    "zone_transition": True,
                },
                "zones_path": "configs_gta/gta_zone_tracklet.yaml",
                "reid_matching": True,
                "geometry_distance_metric": "plane",
                "geometry_t_min_m": 14.0,
                "geometry_t_distant_m": 0.0,
                "geometry_mid_penalty": 0.15,
                "same_cam_cost_add": 0.25,
                "max_cross_cam_gap_frames": 300,
                "reid_cost_threshold": 0.25,
            },
            "max_history_gap_frames": 30,
            "results_dir": "outputs/configs_gta/zone_tracklet",
        },
        "output": {
            "video_fps": 10,
            "visualize": False,
            "save_video": False,
            "save_video_dir": "outputs/configs_gta/zone_tracklet/videos",
            "output_path": "outputs/configs_gta/zone_tracklet/multicam.mp4",
        },
    }
    dst = OUT_ROOT / "zone_tracklet.yaml"
    dst.write_text(
        "# GTA MCMT: ReID-only association + tracklet zone graph.\n"
        "# Run: python run.py --config configs_gta/zone_tracklet.yaml\n\n"
        + yaml.dump(cfg, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


def main() -> None:
    if not (OUT_ROOT / "gta_zone_tracklet.yaml").is_file():
        raise FileNotFoundError(
            "Missing configs_gta/gta_zone_tracklet.yaml — create it before running."
        )

    write_gta_zone_polygons()
    write_zone_tracklet_run_config()

    n = 0
    for src, dst in _collect_sources():
        if not src.is_file():
            print(f"SKIP missing: {src.relative_to(_ROOT)}")
            continue
        raw = src.read_text(encoding="utf-8")
        cfg = yaml.safe_load(raw) or {}
        patched = patch_config(cfg, dst.relative_to(OUT_ROOT))
        dst.parent.mkdir(parents=True, exist_ok=True)
        body = yaml.dump(patched, sort_keys=False, allow_unicode=True)
        dst_rel = dst.relative_to(_ROOT)
        dst.write_text(_rewrite_run_comment(body, dst_rel), encoding="utf-8")
        print(f"Wrote {dst_rel.as_posix()}")
        n += 1

    readme = OUT_ROOT / "README.md"
    readme.write_text(
        """# GTA MCMT ablation configs

Generated from S02 ablation templates with GTA dataset paths.

## Dataset

- Sources: `datasets/gta_mcmt/cam-{0,1,2,3}`
- ROI: `auto` (`cam-N/roi.jpg`)
- GT eval: `python scripts/eval_gta_mcmt.py --pred-dir outputs/configs_gta/<run>/per_cam --apply-roi`

## Zone graph

- Tracklet mode: `configs_gta/gta_zone_tracklet.yaml`
- Snapshot mode: `configs_gta/gta_zone_polygons.yaml`
- Preview: `python scripts/generate_gta_mcmt_zone_preview.py --config configs_gta/gta_zone_tracklet.yaml`

Entry lanes `2,4,6,8` → exit lanes `1,3,5,7`. Merged on cam-1: `1≡{1,2}`, `5≡{5,6}`.

## Quick runs

```bash
python run.py --config configs_gta/baseline.yaml
python run.py --config configs_gta/zone_tracklet.yaml
python run.py --config configs_gta/assoc_ablation/+zone_tracklet.yaml
```

## Regenerate

```bash
python scripts/generate_configs_gta.py
```
""",
        encoding="utf-8",
    )
    print(f"\nDone: {n} run configs + zone_tracklet + README")


if __name__ == "__main__":
    main()
